Testing
unosquare/uno-react pull request #453
Opened 2021-01-11 21:16 UTC by ncamacho0

Still working

2021-01-25 04:09 UTC, geoperez requested changes

2021-01-25 04:09 UTC, geoperez commented on src/hooks/usePersistedState.test.ts
> +    const defaultValue: string = 'unosquareToken';
Check the failures.

2021-01-25 04:29 UTC, ncamacho0 commented on src/hooks/usePersistedState.test.ts
> +    const defaultValue: string = 'unosquareToken';
i think that was already fixed

2021-02-01 18:44 UTC, geoperez approved these changes

2021-02-01 18:44 UTC, merged